## Chap4. Data type and structure

### 4.1 data type

In [1]:
# int
a = 10
type(a)

int

In [2]:
#float
a = 1.
type(a)

float

In [3]:
#string
s = 'this is a string object'
type(s)

str

In [4]:
# methods in string
s.capitalize()

'This is a string object'

In [5]:
# methods in string
s.split()

['this', 'is', 'a', 'string', 'object']

In [17]:
# methods in string
s.find('string')
#will return the index number of 'string'

10

In [18]:
s.replace(' ','|')

'this|is|a|string|object'

In [14]:
# all these methods do not change the string itself, if we need to modify an obejct ,we need to use s = s.replace(' ','|')
s

'this is a string object'

### 4.2 Basic data structure

#### Basic data structure includes tuple, list, dictionary and set

In [21]:
#Tuple
t = (1,2,'time',2)
type(t)

tuple

In [22]:
t[2]

'time'

In [23]:
t.count(2)

2

In [25]:
t.index('time')
#index starts from 0 like list

2

In [9]:
#list
list1 = [1,3,4,'data']
type(list1)

list

In [10]:
list1.append(['a', 'b'])
list1

[1, 3, 4, 'data', ['a', 'b']]

In [11]:
list1.remove(1)
list1
#will remove the first occurrence of object

[3, 4, 'data', ['a', 'b']]

In [12]:
p = list1.pop(0)
p
#pop use the index 

3

In [13]:
list1[0:2]
#return the first and the second element

[4, 'data']

In [19]:
li=[1,3,4,5,6,7,3]
li.sort()
li

[1, 3, 3, 4, 5, 6, 7]

In [20]:
li.reverse()
li

[7, 6, 5, 4, 3, 3, 1]

In [21]:
li.insert(0,'a')
li
#insert 'a' before index 0

['a', 7, 6, 5, 4, 3, 3, 1]

### 4.3 Numpy

In [2]:
import numpy as np

In [43]:
a = np.array([1,2,4,3,2,5,6])
type(a)

numpy.ndarray

In [24]:
a[0:2]

array([1, 2])

In [25]:
a.sum()

23

In [26]:
a*2

array([ 2,  4,  8,  6,  4, 10, 12])

In [28]:
b = np.array([a, a*2])
b

array([[ 1,  2,  4,  3,  2,  5,  6],
       [ 2,  4,  8,  6,  4, 10, 12]])

In [30]:
b[0,5]
# the first element is the row index, and the second is the column index

5

In [31]:
b.sum(axis=0)
# sum along axis 0, column-wise sum

array([ 3,  6, 12,  9,  6, 15, 18])

In [ ]:
b.sum(axis=1)
# sum along axis 1, row-wise sum

In [33]:
c = np.zeros((2,3))
c
#create a new array with 2 rows and 3 columns, and all the elements equal to zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
d = np.ones_like(c)
d
#create a new array with the same structure as c but all the elements equal to one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
#boradcast
r = np.random.standard_normal((4,3))
s = np.random.standard_normal((4,3))
r+s

array([[ 1.13336545, -0.07873128, -0.12939529],
       [ 1.10664352, -0.39972184,  2.59277554],
       [ 0.99212198,  0.6305855 ,  0.30688763],
       [-0.79151266,  0.49418746, -0.85142058]])

In [36]:
2*r+3

array([[ 5.22090654,  3.2258554 ,  3.53453208],
       [ 5.29442734,  4.3763459 ,  4.29726157],
       [ 3.4660022 ,  3.84921111,  2.52499341],
       [-0.64453078,  3.37897678, -0.96748414]])

In [45]:
t = np.array(([1,1,3], [2,2,2]))
p = np.array(([1,1,3]))
t*p

array([[1, 1, 9],
       [2, 2, 6]])

## Chap6. Financial Time Series

### 5.1 Pandas basic

In [1]:
import pandas as pd

In [66]:
#dataframe
df = pd.DataFrame([1,3,5,6,7], columns=['numbers'], index =['a','b','c','d','e'])
df

numbers
a        1
b        3
c        5
d        6
e        7

In [67]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [68]:
df.columns

Index(['numbers'], dtype='object')

In [69]:
df.loc['a']
#loc for index based and iloc for positional based

numbers    1
Name: a, dtype: int64

In [70]:
df.iloc[1:3]

numbers
b        3
c        5

In [71]:
df.sum()

numbers    22
dtype: int64

In [72]:
#generate a new column
df['float'] = (1.2, 3.4, 2.4, 4.1, 5.6)
df

numbers  float
a        1    1.2
b        3    3.4
c        5    2.4
d        6    4.1
e        7    5.6

In [73]:
# generate a new column with predefined index
df['name']=pd.DataFrame(['Luke', 'Carrey', 'Jake', 'Lucy', 'Mike'], index = ['b','a','c','e','d'])
df

numbers  float    name
a        1    1.2  Carrey
b        3    3.4    Luke
c        5    2.4    Jake
d        6    4.1    Mike
e        7    5.6    Lucy

In [18]:
#add observation
df = df.append(pd.DataFrame({'numbers':100, 'float':3.6,'name':'Mark'},index =['z']))
df

numbers  float    name
a        1    1.2  Carrey
b        3    3.4    Luke
c        5    2.4    Jake
d        6    4.1    Mike
e        7    5.6    Lucy
z      100    3.6    Mark

In [19]:
#add new column
df = df.join(pd.DataFrame([1,6,8,7,9], index=['b','a','c','e','f'], columns=['integer']),how='outer')
df
#pandas assume the missing value is NaN for the new index

numbers  float    name  integer
a      1.0    1.2  Carrey      6.0
b      3.0    3.4    Luke      1.0
c      5.0    2.4    Jake      8.0
d      6.0    4.1    Mike      NaN
e      7.0    5.6    Lucy      7.0
f      NaN    NaN     NaN      9.0
z    100.0    3.6    Mark      NaN

In [22]:
df.loc['f']=[3,5.6,'Jay',9]
df

numbers  float    name  integer
a      1.0    1.2  Carrey      6.0
b      3.0    3.4    Luke      1.0
c      5.0    2.4    Jake      8.0
d      6.0    4.1    Mike      NaN
e      7.0    5.6    Lucy      7.0
f      3.0    5.6     Jay      9.0
z    100.0    3.6    Mark      NaN

In [43]:
#generate random numbers
a = np.random.standard_normal((7,4))
a.round(3)

array([[-0.939, -0.78 , -0.649,  2.851],
       [-0.498,  0.608,  0.882,  0.409],
       [ 2.785, -0.212, -0.629, -0.678],
       [ 0.788,  0.165, -1.223, -0.127],
       [ 1.306, -0.724,  0.858, -2.03 ],
       [-0.666, -0.923, -0.103, -0.955],
       [-0.91 , -0.56 , -0.077,  0.061]])

In [44]:
#convert an array to a dataframe
df1= pd.DataFrame(a)
df1

0         1         2         3
0 -0.939181 -0.779529 -0.648674  2.850916
1 -0.498137  0.607654  0.881503  0.408630
2  2.785468 -0.211583 -0.629224 -0.678447
3  0.788097  0.165342 -1.223311 -0.126751
4  1.306100 -0.723848  0.857826 -2.029658
5 -0.665599 -0.923263 -0.102986 -0.955275
6 -0.909991 -0.560493 -0.076503  0.060968

In [45]:
df1.columns=['No1', 'No2', 'No3','No4']
df1

No1       No2       No3       No4
0 -0.939181 -0.779529 -0.648674  2.850916
1 -0.498137  0.607654  0.881503  0.408630
2  2.785468 -0.211583 -0.629224 -0.678447
3  0.788097  0.165342 -1.223311 -0.126751
4  1.306100 -0.723848  0.857826 -2.029658
5 -0.665599 -0.923263 -0.102986 -0.955275
6 -0.909991 -0.560493 -0.076503  0.060968

In [46]:
#time series
dates = pd.date_range('2021-1-1',periods=7,freq='M')
dates

DatetimeIndex(['2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31'],
              dtype='datetime64[ns]', freq='M')

In [47]:
df1.index = dates
df1
#add date as index

No1       No2       No3       No4
2021-01-31 -0.939181 -0.779529 -0.648674  2.850916
2021-02-28 -0.498137  0.607654  0.881503  0.408630
2021-03-31  2.785468 -0.211583 -0.629224 -0.678447
2021-04-30  0.788097  0.165342 -1.223311 -0.126751
2021-05-31  1.306100 -0.723848  0.857826 -2.029658
2021-06-30 -0.665599 -0.923263 -0.102986 -0.955275
2021-07-31 -0.909991 -0.560493 -0.076503  0.060968

In [48]:
df1.sum(axis=0)
#sum according to column

No1    1.866756
No2   -2.425719
No3   -0.941368
No4   -0.469619
dtype: float64

In [49]:
df1.sum(axis=1)
#sum according to row

2021-01-31    0.483531
2021-02-28    1.399649
2021-03-31    1.266215
2021-04-30   -0.396623
2021-05-31   -0.589580
2021-06-30   -2.647123
2021-07-31   -1.486019
Freq: M, dtype: float64

In [50]:
df1.describe()

No1       No2       No3       No4
count  7.000000  7.000000  7.000000  7.000000
mean   0.266679 -0.346531 -0.134481 -0.067088
std    1.413583  0.562576  0.786974  1.515219
min   -0.939181 -0.923263 -1.223311 -2.029658
25%   -0.787795 -0.751689 -0.638949 -0.816861
50%   -0.498137 -0.560493 -0.102986 -0.126751
75%    1.047098 -0.023120  0.390662  0.234799
max    2.785468  0.607654  0.881503  2.850916

In [51]:
np.sqrt(df1).sum()

C:\Anaconda3201910\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


No1    3.699568
No2    1.186145
No3    1.865073
No4    2.574623
dtype: float64

In [52]:
df1['group']= (1,2,1,2,3,3,1)

In [53]:
df1.columns

Index(['No1', 'No2', 'No3', 'No4', 'group'], dtype='object')

In [54]:
#iloc is used to refer to the index of the column or row
df1.iloc[0,1] #first row and second column

-0.7795291985884851

In [55]:
#while loc is used to refer the name of the column or row
df1.loc['2021-01-31',:]

No1     -0.939181
No2     -0.779529
No3     -0.648674
No4      2.850916
group    1.000000
Name: 2021-01-31 00:00:00, dtype: float64

In [56]:
df1.loc[:,'No4']

2021-01-31    2.850916
2021-02-28    0.408630
2021-03-31   -0.678447
2021-04-30   -0.126751
2021-05-31   -2.029658
2021-06-30   -0.955275
2021-07-31    0.060968
Freq: M, Name: No4, dtype: float64

In [58]:
groups = df1.groupby('group')
groups.mean()

No1       No2       No3       No4
group                                        
1      0.312098 -0.517201 -0.451467  0.744479
2      0.144980  0.386498 -0.170904  0.140939
3      0.320250 -0.823555  0.377420 -1.492467

In [64]:
!pip install pandas_datareader

In [78]:
#import financial data
from pandas_datareader import data
start_date = '2021-01-01'
end_date = '2021-04-01'
df_stock = data.DataReader(['AAPL', 'MSFT'],"yahoo", start_date, end_date)

In [79]:
df_stock 

Attributes   Adj Close                   Close                    High  \
Symbols           AAPL        MSFT        AAPL        MSFT        AAPL   
Date                                                                     
2021-01-04  129.216919  217.189774  129.410004  217.690002  133.610001   
2021-01-05  130.814514  217.399292  131.009995  217.899994  131.740005   
2021-01-06  126.411102  211.762268  126.599998  212.250000  131.050003   
2021-01-07  130.724655  217.788391  130.919998  218.289993  131.630005   
2021-01-08  131.852966  219.115341  132.050003  219.619995  132.630005   
...                ...         ...         ...         ...         ...   
2021-03-26  121.209999  236.479996  121.209999  236.479996  121.480003   
2021-03-29  121.389999  235.240005  121.389999  235.240005  122.580002   
2021-03-30  119.900002  231.850006  119.900002  231.850006  120.400002   
2021-03-31  122.150002  235.770004  122.150002  235.770004  123.519997   
2021-04-01  123.000000  242.350006  123.000000  242.350006  124.180000   

Attributes                     Low                    Open              \
Symbols           MSFT        AAPL        MSFT        AAPL        MSFT   
Date                                                                     
2021-01-04  223.000000  126.760002  214.809998  133.520004  222.529999   
2021-01-05  218.520004  128.429993  215.699997  128.889999  217.259995   
2021-01-06  216.490005  126.379997  211.940002  127.720001  212.169998   
2021-01-07  219.339996  127.860001  213.710007  128.360001  214.039993   
2021-01-08  220.580002  130.229996  217.029999  132.429993  218.679993   
...                ...         ...         ...         ...         ...   
2021-03-26  236.710007  118.919998  231.550003  120.349998  231.550003   
2021-03-29  236.800003  120.730003  231.880005  121.650002  236.589996   
2021-03-30  233.850006  118.860001  231.100006  120.110001  233.529999   
2021-03-31  239.100006  121.150002  232.389999  121.650002  232.910004   
2021-04-01  242.839996  122.489998  238.050003  123.660004  238.470001   

Attributes       Volume              
Symbols            AAPL        MSFT  
Date                                 
2021-01-04  143301900.0  37130100.0  
2021-01-05   97664900.0  23823000.0  
2021-01-06  155088000.0  35930700.0  
2021-01-07  109578200.0  27694500.0  
2021-01-08  105158200.0  22956200.0  
...                 ...         ...  
2021-03-26   93958900.0  25471700.0  
2021-03-29   80819200.0  25227500.0  
2021-03-30   85671900.0  24792000.0  
2021-03-31  118323800.0  43623500.0  
2021-04-01   74957400.0  30312000.0  

[62 rows x 12 columns]

In [80]:
df_stock['Close'].plot(figsize=(8,6))

In [83]:
df_stock.columns

MultiIndex([('Adj Close', 'AAPL'),
            ('Adj Close', 'MSFT'),
            (    'Close', 'AAPL'),
            (    'Close', 'MSFT'),
            (     'High', 'AAPL'),
            (     'High', 'MSFT'),
            (      'Low', 'AAPL'),
            (      'Low', 'MSFT'),
            (     'Open', 'AAPL'),
            (     'Open', 'MSFT'),
            (   'Volume', 'AAPL'),
            (   'Volume', 'MSFT')],
           names=['Attributes', 'Symbols'])

In [84]:
#generate log return
df_stock['Return','AAPL' ] = np.log(df_stock['Close','AAPL'] / df_stock['Close','AAPL'].shift(1))

In [85]:
df_stock['Return','MSFT' ] = np.log(df_stock['Close','MSFT'] / df_stock['Close','MSFT'].shift(1))

In [86]:
df_stock

Attributes   Adj Close                   Close                    High  \
Symbols           AAPL        MSFT        AAPL        MSFT        AAPL   
Date                                                                     
2021-01-04  129.216919  217.189774  129.410004  217.690002  133.610001   
2021-01-05  130.814514  217.399292  131.009995  217.899994  131.740005   
2021-01-06  126.411102  211.762268  126.599998  212.250000  131.050003   
2021-01-07  130.724655  217.788391  130.919998  218.289993  131.630005   
2021-01-08  131.852966  219.115341  132.050003  219.619995  132.630005   
...                ...         ...         ...         ...         ...   
2021-03-26  121.209999  236.479996  121.209999  236.479996  121.480003   
2021-03-29  121.389999  235.240005  121.389999  235.240005  122.580002   
2021-03-30  119.900002  231.850006  119.900002  231.850006  120.400002   
2021-03-31  122.150002  235.770004  122.150002  235.770004  123.519997   
2021-04-01  123.000000  242.350006  123.000000  242.350006  124.180000   

Attributes                     Low                    Open              \
Symbols           MSFT        AAPL        MSFT        AAPL        MSFT   
Date                                                                     
2021-01-04  223.000000  126.760002  214.809998  133.520004  222.529999   
2021-01-05  218.520004  128.429993  215.699997  128.889999  217.259995   
2021-01-06  216.490005  126.379997  211.940002  127.720001  212.169998   
2021-01-07  219.339996  127.860001  213.710007  128.360001  214.039993   
2021-01-08  220.580002  130.229996  217.029999  132.429993  218.679993   
...                ...         ...         ...         ...         ...   
2021-03-26  236.710007  118.919998  231.550003  120.349998  231.550003   
2021-03-29  236.800003  120.730003  231.880005  121.650002  236.589996   
2021-03-30  233.850006  118.860001  231.100006  120.110001  233.529999   
2021-03-31  239.100006  121.150002  232.389999  121.650002  232.910004   
2021-04-01  242.839996  122.489998  238.050003  123.660004  238.470001   

Attributes       Volume                Return            
Symbols            AAPL        MSFT      AAPL      MSFT  
Date                                                     
2021-01-04  143301900.0  37130100.0       NaN       NaN  
2021-01-05   97664900.0  23823000.0  0.012288  0.000964  
2021-01-06  155088000.0  35930700.0 -0.034241 -0.026271  
2021-01-07  109578200.0  27694500.0  0.033554  0.028060  
2021-01-08  105158200.0  22956200.0  0.008594  0.006074  
...                 ...         ...       ...       ...  
2021-03-26   93958900.0  25471700.0  0.005128  0.017662  
2021-03-29   80819200.0  25227500.0  0.001484 -0.005257  
2021-03-30   85671900.0  24792000.0 -0.012350 -0.014516  
2021-03-31  118323800.0  43623500.0  0.018592  0.016766  
2021-04-01   74957400.0  30312000.0  0.006935  0.027526  

[62 rows x 14 columns]

In [88]:
#rolling mean
df_stock['42d','AAPL' ] = df_stock['Close','AAPL'].rolling(42).mean()

In [89]:
df_stock['42d','MSFT' ] = df_stock['Close','MSFT'].rolling(42).mean()
df_stock

Attributes   Adj Close                   Close                    High  \
Symbols           AAPL        MSFT        AAPL        MSFT        AAPL   
Date                                                                     
2021-01-04  129.216919  217.189774  129.410004  217.690002  133.610001   
2021-01-05  130.814514  217.399292  131.009995  217.899994  131.740005   
2021-01-06  126.411102  211.762268  126.599998  212.250000  131.050003   
2021-01-07  130.724655  217.788391  130.919998  218.289993  131.630005   
2021-01-08  131.852966  219.115341  132.050003  219.619995  132.630005   
...                ...         ...         ...         ...         ...   
2021-03-26  121.209999  236.479996  121.209999  236.479996  121.480003   
2021-03-29  121.389999  235.240005  121.389999  235.240005  122.580002   
2021-03-30  119.900002  231.850006  119.900002  231.850006  120.400002   
2021-03-31  122.150002  235.770004  122.150002  235.770004  123.519997   
2021-04-01  123.000000  242.350006  123.000000  242.350006  124.180000   

Attributes                     Low                    Open              \
Symbols           MSFT        AAPL        MSFT        AAPL        MSFT   
Date                                                                     
2021-01-04  223.000000  126.760002  214.809998  133.520004  222.529999   
2021-01-05  218.520004  128.429993  215.699997  128.889999  217.259995   
2021-01-06  216.490005  126.379997  211.940002  127.720001  212.169998   
2021-01-07  219.339996  127.860001  213.710007  128.360001  214.039993   
2021-01-08  220.580002  130.229996  217.029999  132.429993  218.679993   
...                ...         ...         ...         ...         ...   
2021-03-26  236.710007  118.919998  231.550003  120.349998  231.550003   
2021-03-29  236.800003  120.730003  231.880005  121.650002  236.589996   
2021-03-30  233.850006  118.860001  231.100006  120.110001  233.529999   
2021-03-31  239.100006  121.150002  232.389999  121.650002  232.910004   
2021-04-01  242.839996  122.489998  238.050003  123.660004  238.470001   

Attributes       Volume                Return                   42d  \
Symbols            AAPL        MSFT      AAPL      MSFT        AAPL   
Date                                                                  
2021-01-04  143301900.0  37130100.0       NaN       NaN         NaN   
2021-01-05   97664900.0  23823000.0  0.012288  0.000964         NaN   
2021-01-06  155088000.0  35930700.0 -0.034241 -0.026271         NaN   
2021-01-07  109578200.0  27694500.0  0.033554  0.028060         NaN   
2021-01-08  105158200.0  22956200.0  0.008594  0.006074         NaN   
...                 ...         ...       ...       ...         ...   
2021-03-26   93958900.0  25471700.0  0.005128  0.017662  127.376428   
2021-03-29   80819200.0  25227500.0  0.001484 -0.005257  126.884285   
2021-03-30   85671900.0  24792000.0 -0.012350 -0.014516  126.475000   
2021-03-31  118323800.0  43623500.0  0.018592  0.016766  126.241428   
2021-04-01   74957400.0  30312000.0  0.006935  0.027526  125.976190   

Attributes              
Symbols           MSFT  
Date                    
2021-01-04         NaN  
2021-01-05         NaN  
2021-01-06         NaN  
2021-01-07         NaN  
2021-01-08         NaN  
...                ...  
2021-03-26  236.588333  
2021-03-29  236.644048  
2021-03-30  236.475477  
2021-03-31  236.566191  
2021-04-01  236.630477  

[62 rows x 16 columns]

## Chap7. Input and output

In [1]:
import pickle